# Generated by Django 4.2.1 on 2023-05-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatos',
            old_name='codigo_cliente',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='contatos',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
