# Generated by Django 4.2.1 on 2023-05-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_cliente_user',
        ),
    ]
