# Generated by Django 4.2.1 on 2023-05-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='nome_cliente_conta',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='dono_endereco',
            new_name='cliente',
        ),
    ]
