# Generated by Django 4.2.1 on 2023-05-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastbank', '0002_alter_cliente_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='estado',
            new_name='UF',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
