# Generated by Django 4.2.1 on 2023-05-29 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fastbank', '0002_rename_codigo_cliente_contatos_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='destinatario',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='operacao',
            field=models.CharField(choices=[('TD', 'Transferência Débito'), ('TC', 'Transferência Crédito'), ('DP', 'Depósito em Conta'), ('PX', 'Transferência PIX')], default='TD', max_length=2),
        ),
    ]
