# Generated by Django 4.2.1 on 2023-05-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastbank', '0002_remove_cliente_unique_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
