# Generated by Django 4.1.7 on 2023-05-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastbank', '0003_rename_estado_endereco_uf_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='data_nascimento_criacao',
            new_name='data_nascimento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateField(auto_now=True),
        ),
    ]
